/**
 * Public client check-in form — token-authenticated, no login required.
 *
 * Accessed via emailed link: /portal/checkin/[token]
 * The token is a one-time or time-limited secret generated by the partner
 * and validated by the publicProcedure checkin.submitCheckin tRPC endpoint.
 *
 * This route lives outside the portal (protected) group intentionally so
 * clients can fill it in without an account.
 */

"use client";

import { useState } from "react";
import { useParams } from "next/navigation";
import { trpc } from "@/lib/trpc/client";

// ── Types ─────────────────────────────────────────────────────────────────────

interface CheckinFormData {
  weightKg: string;
  waistCm: string;
  hipCm: string;
  energyLevel: number;
  sleepQuality: number;
  stressLevel: number;
  hungerLevel: number;
  digestiveHealth: number;
  adherencePct: number;
  trainingAdherence: number;
  notes: string;
}

// ── Scale Input ───────────────────────────────────────────────────────────────

function ScaleInput({
  label,
  value,
  onChange,
  lowLabel,
  highLabel,
}: {
  label: string;
  value: number;
  onChange: (v: number) => void;
  lowLabel: string;
  highLabel: string;
}) {
  return (
    <div style={{ marginBottom: "24px" }}>
      <label style={{ fontSize: "14px", fontWeight: 600, color: "#1a1a2e", display: "block", marginBottom: "8px" }}>
        {label}
      </label>
      <div style={{ display: "flex", gap: "6px", alignItems: "center" }}>
        <span style={{ fontSize: "12px", color: "#6b7280", minWidth: "60px" }}>{lowLabel}</span>
        {Array.from({ length: 10 }, (_, i) => i + 1).map((n) => (
          <button
            key={n}
            type="button"
            onClick={() => onChange(n)}
            style={{
              width: "36px",
              height: "36px",
              borderRadius: "8px",
              border: value === n ? "2px solid #1a1a2e" : "1px solid #e2e8f0",
              backgroundColor: value === n ? "#1a1a2e" : "#ffffff",
              color: value === n ? "#ffffff" : "#374151",
              fontSize: "14px",
              fontWeight: 600,
              cursor: "pointer",
              transition: "all 0.15s",
            }}
          >
            {n}
          </button>
        ))}
        <span style={{ fontSize: "12px", color: "#6b7280", minWidth: "60px", textAlign: "right" }}>{highLabel}</span>
      </div>
    </div>
  );
}

// ── Slider Input ──────────────────────────────────────────────────────────────

function SliderInput({
  label,
  value,
  onChange,
  suffix,
}: {
  label: string;
  value: number;
  onChange: (v: number) => void;
  suffix: string;
}) {
  return (
    <div style={{ marginBottom: "24px" }}>
      <label style={{ fontSize: "14px", fontWeight: 600, color: "#1a1a2e", display: "block", marginBottom: "8px" }}>
        {label}: <span style={{ color: "#3b82f6" }}>{value}{suffix}</span>
      </label>
      <input
        type="range"
        min={0}
        max={100}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        style={{ width: "100%", accentColor: "#1a1a2e" }}
      />
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: "12px", color: "#9ca3af" }}>
        <span>0{suffix}</span>
        <span>100{suffix}</span>
      </div>
    </div>
  );
}

// ── Page Component ────────────────────────────────────────────────────────────

export default function PublicCheckinPage() {
  const params = useParams();
  const token = params.token as string;

  const [submitted, setSubmitted] = useState(false);
  const [formData, setFormData] = useState<CheckinFormData>({
    weightKg: "",
    waistCm: "",
    hipCm: "",
    energyLevel: 5,
    sleepQuality: 5,
    stressLevel: 5,
    hungerLevel: 5,
    digestiveHealth: 5,
    adherencePct: 80,
    trainingAdherence: 80,
    notes: "",
  });

  const updateField = <K extends keyof CheckinFormData>(field: K, value: CheckinFormData[K]) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submitMutation = trpc.checkin.submitCheckin.useMutation({
    onSuccess: () => {
      setSubmitted(true);
    },
    onError: (err) => {
      setError(err.message);
      setSubmitting(false);
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);

    submitMutation.mutate({
      token,
      weightKg: parseFloat(formData.weightKg),
      waistCm: formData.waistCm ? parseFloat(formData.waistCm) : undefined,
      hipCm: formData.hipCm ? parseFloat(formData.hipCm) : undefined,
      energyLevel: formData.energyLevel,
      sleepQuality: formData.sleepQuality,
      stressLevel: formData.stressLevel,
      hungerLevel: formData.hungerLevel,
      digestiveHealth: formData.digestiveHealth,
      adherencePct: formData.adherencePct,
      trainingAdherence: formData.trainingAdherence,
      notes: formData.notes || undefined,
    });
  };

  if (submitted) {
    return (
      <div
        style={{
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#f8fafc",
          fontFamily: "system-ui, -apple-system, sans-serif",
        }}
      >
        <div
          style={{
            textAlign: "center",
            padding: "60px 40px",
            background: "#ffffff",
            borderRadius: "16px",
            border: "1px solid #e2e8f0",
            maxWidth: "480px",
          }}
        >
          <div style={{ fontSize: "64px", marginBottom: "20px" }}>&#10003;</div>
          <h1 style={{ fontSize: "24px", fontWeight: 700, color: "#1a1a2e", marginBottom: "12px" }}>
            Check-in inviato!
          </h1>
          <p style={{ fontSize: "16px", color: "#6b7280", lineHeight: 1.6 }}>
            Grazie per aver compilato il check-in. Il tuo nutrizionista lo revisionera a breve.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#f8fafc",
        fontFamily: "system-ui, -apple-system, sans-serif",
      }}
    >
      <div style={{ maxWidth: "640px", margin: "0 auto", padding: "32px 16px" }}>
        {/* Header */}
        <div style={{ textAlign: "center", marginBottom: "32px" }}>
          <h1 style={{ fontSize: "24px", fontWeight: 700, color: "#1a1a2e", marginBottom: "8px" }}>
            Check-in Settimanale
          </h1>
          <p style={{ color: "#6b7280", fontSize: "15px" }}>
            Compila il questionario per aggiornare il tuo nutrizionista sui tuoi progressi.
          </p>
        </div>

        <form onSubmit={handleSubmit}>
          {/* Weight & Measurements */}
          <div
            style={{
              background: "#ffffff",
              border: "1px solid #e2e8f0",
              borderRadius: "12px",
              padding: "24px",
              marginBottom: "20px",
            }}
          >
            <h2 style={{ fontSize: "16px", fontWeight: 700, color: "#1a1a2e", marginBottom: "20px" }}>
              Misurazioni
            </h2>

            <div style={{ marginBottom: "16px" }}>
              <label style={{ fontSize: "14px", fontWeight: 600, color: "#1a1a2e", display: "block", marginBottom: "6px" }}>
                Peso (kg) *
              </label>
              <input
                type="number"
                step="0.1"
                required
                value={formData.weightKg}
                onChange={(e) => updateField("weightKg", e.target.value)}
                placeholder="es. 78.5"
                style={{
                  width: "100%",
                  padding: "12px 16px",
                  border: "1px solid #e2e8f0",
                  borderRadius: "8px",
                  fontSize: "16px",
                  boxSizing: "border-box",
                }}
              />
            </div>

            <div style={{ display: "flex", gap: "16px" }}>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: "14px", fontWeight: 600, color: "#1a1a2e", display: "block", marginBottom: "6px" }}>
                  Vita (cm)
                </label>
                <input
                  type="number"
                  step="0.1"
                  value={formData.waistCm}
                  onChange={(e) => updateField("waistCm", e.target.value)}
                  placeholder="es. 82"
                  style={{
                    width: "100%",
                    padding: "12px 16px",
                    border: "1px solid #e2e8f0",
                    borderRadius: "8px",
                    fontSize: "16px",
                    boxSizing: "border-box",
                  }}
                />
              </div>
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: "14px", fontWeight: 600, color: "#1a1a2e", display: "block", marginBottom: "6px" }}>
                  Fianchi (cm)
                </label>
                <input
                  type="number"
                  step="0.1"
                  value={formData.hipCm}
                  onChange={(e) => updateField("hipCm", e.target.value)}
                  placeholder="es. 96"
                  style={{
                    width: "100%",
                    padding: "12px 16px",
                    border: "1px solid #e2e8f0",
                    borderRadius: "8px",
                    fontSize: "16px",
                    boxSizing: "border-box",
                  }}
                />
              </div>
            </div>
          </div>

          {/* Wellbeing Scales */}
          <div
            style={{
              background: "#ffffff",
              border: "1px solid #e2e8f0",
              borderRadius: "12px",
              padding: "24px",
              marginBottom: "20px",
            }}
          >
            <h2 style={{ fontSize: "16px", fontWeight: 700, color: "#1a1a2e", marginBottom: "20px" }}>
              Benessere
            </h2>

            <ScaleInput
              label="Livello di energia"
              value={formData.energyLevel}
              onChange={(v) => updateField("energyLevel", v)}
              lowLabel="Basso"
              highLabel="Alto"
            />
            <ScaleInput
              label="Qualita del sonno"
              value={formData.sleepQuality}
              onChange={(v) => updateField("sleepQuality", v)}
              lowLabel="Scarso"
              highLabel="Ottimo"
            />
            <ScaleInput
              label="Livello di stress"
              value={formData.stressLevel}
              onChange={(v) => updateField("stressLevel", v)}
              lowLabel="Basso"
              highLabel="Alto"
            />
            <ScaleInput
              label="Fame / appetito"
              value={formData.hungerLevel}
              onChange={(v) => updateField("hungerLevel", v)}
              lowLabel="Bassa"
              highLabel="Alta"
            />
            <ScaleInput
              label="Salute digestiva"
              value={formData.digestiveHealth}
              onChange={(v) => updateField("digestiveHealth", v)}
              lowLabel="Scarsa"
              highLabel="Ottima"
            />
          </div>

          {/* Adherence */}
          <div
            style={{
              background: "#ffffff",
              border: "1px solid #e2e8f0",
              borderRadius: "12px",
              padding: "24px",
              marginBottom: "20px",
            }}
          >
            <h2 style={{ fontSize: "16px", fontWeight: 700, color: "#1a1a2e", marginBottom: "20px" }}>
              Aderenza
            </h2>

            <SliderInput
              label="Aderenza al piano alimentare"
              value={formData.adherencePct}
              onChange={(v) => updateField("adherencePct", v)}
              suffix="%"
            />
            <SliderInput
              label="Aderenza al piano di allenamento"
              value={formData.trainingAdherence}
              onChange={(v) => updateField("trainingAdherence", v)}
              suffix="%"
            />
          </div>

          {/* Notes */}
          <div
            style={{
              background: "#ffffff",
              border: "1px solid #e2e8f0",
              borderRadius: "12px",
              padding: "24px",
              marginBottom: "28px",
            }}
          >
            <h2 style={{ fontSize: "16px", fontWeight: 700, color: "#1a1a2e", marginBottom: "12px" }}>
              Note aggiuntive
            </h2>
            <textarea
              value={formData.notes}
              onChange={(e) => updateField("notes", e.target.value)}
              placeholder="Qualsiasi cosa tu voglia comunicare al tuo nutrizionista..."
              rows={4}
              style={{
                width: "100%",
                padding: "12px 16px",
                border: "1px solid #e2e8f0",
                borderRadius: "8px",
                fontSize: "15px",
                resize: "vertical",
                boxSizing: "border-box",
                fontFamily: "inherit",
              }}
            />
          </div>

          {/* Error */}
          {error && (
            <div
              style={{
                padding: "12px 16px",
                backgroundColor: "#fef2f2",
                border: "1px solid #fecaca",
                borderRadius: "8px",
                color: "#dc2626",
                fontSize: "14px",
                marginBottom: "16px",
              }}
            >
              {error}
            </div>
          )}

          {/* Submit */}
          <button
            type="submit"
            disabled={submitting}
            style={{
              width: "100%",
              padding: "16px",
              backgroundColor: submitting ? "#6b7280" : "#1a1a2e",
              color: "#ffffff",
              border: "none",
              borderRadius: "12px",
              fontSize: "16px",
              fontWeight: 700,
              cursor: submitting ? "not-allowed" : "pointer",
              transition: "opacity 0.15s",
            }}
          >
            {submitting ? "Invio in corso..." : "Invia Check-in"}
          </button>
        </form>
      </div>
    </div>
  );
}
