/**
 * DIAGNOSTIC (read-only, NOT wired into generation) — #food-enrichment Stage 2.
 *
 * Generates plans for ONE representative athlete at TWO day-types — a LOW-CARB
 * day and a HIGH-CARB day — using the per-ingredient solver, and:
 *   - prints prescription vs delivered kcal/protein/carbs/fat/fibre/sodium (+%delta)
 *   - prints each meal's full ingredient list with grams
 *   - FLAGS every filler addition (ingredient not in the source template) and any
 *     out-of-bound / zero-gram ingredient (should be none)
 *   - WRITES a human-readable markdown artifact for clinical review to
 *     scripts/out/stage2-sample-plans.md
 *
 * Asserts nothing. Run: bun run scripts/diag-stage2-plans.ts
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createMealPlan } from "../src/engine/meal-plan/planner";
import { ALL_TEMPLATES } from "../src/data/meals/templates";
import type { MacroTargets } from "../src/engine/types";

// One representative athlete (~80 kg male), two day-types.
const DAYS: { label: string; macros: MacroTargets; mealCount: number }[] = [
  { label: "LOW-CARB day", macros: rx(170, 90, 90, "rest"), mealCount: 4 },
  { label: "HIGH-CARB day", macros: rx(165, 60, 320, "training"), mealCount: 5 },
];

function rx(proteinG: number, fatG: number, carbG: number, dayType: MacroTargets["dayType"]): MacroTargets {
  return { proteinG, fatG, carbG, totalKcal: proteinG * 4 + carbG * 4 + fatG * 9, dayType };
}

function pct(a: number, t: number): string {
  const d = t ? ((a - t) / t) * 100 : 0;
  return (d >= 0 ? "+" : "") + d.toFixed(1) + "%";
}

const r1 = (n: number) => (Math.round(n * 10) / 10).toFixed(1);

// Accumulate markdown for the clinical-review artifact.
const md: string[] = [];
md.push("# Stage 2 — Sample Meal Plans");
md.push("");
md.push(
  "_Per-ingredient gram solver with joint, kcal-headroom-bounded fillers. " +
    "Generated by `scripts/diag-stage2-plans.ts` for async clinical review. " +
    "Macros are summed from the v3 food database (Calories column, not 4·P+4·C+9·F)._"
);
md.push("");

let allWithinPair = true;
let totalBadGrams = 0;

for (const { label, macros, mealCount } of DAYS) {
  const plan = createMealPlan(ALL_TEMPLATES, {
    dayType: macros.dayType,
    macroTargets: macros,
    mealCount,
    substitutionsPerSlot: 3,
  });
  const g = plan.actualMacros;
  const fibreFloor = (10 * g.kcal) / 1000;

  // ── console ──────────────────────────────────────────────────────────────
  console.log(`\n══════════ ${label} (${mealCount} meals, ${macros.dayType}) ══════════`);
  console.log(`prescription : kcal ${macros.totalKcal}  P ${macros.proteinG}  C ${macros.carbG}  F ${macros.fatG}`);
  console.log(
    `delivered    : kcal ${g.kcal}(${pct(g.kcal, macros.totalKcal)})  P ${g.proteinG}(${pct(g.proteinG, macros.proteinG)})  C ${g.carbsG}(${pct(g.carbsG, macros.carbG)})  F ${g.fatG}(${pct(g.fatG, macros.fatG)})  fibre ${g.fibreG ?? 0}g  sodium ${g.sodiumMg ?? 0}mg`
  );
  console.log(`fibre floor  : need ≥ ${fibreFloor.toFixed(1)}g/day → ${(g.fibreG ?? 0) >= fibreFloor ? "MET" : "BELOW"};  withinTolerance=${plan.withinTolerance}`);

  // ── markdown ─────────────────────────────────────────────────────────────
  md.push(`## ${label} — ${macros.dayType}, ${mealCount} meals`);
  md.push("");
  md.push("| Macro | Target | Delivered | Δ |");
  md.push("|---|---|---|---|");
  md.push(`| Calories | ${macros.totalKcal} kcal | ${g.kcal} kcal | ${pct(g.kcal, macros.totalKcal)} |`);
  md.push(`| Protein | ${r1(macros.proteinG)} g | ${r1(g.proteinG)} g | ${pct(g.proteinG, macros.proteinG)} |`);
  md.push(`| Carbs | ${r1(macros.carbG)} g | ${r1(g.carbsG)} g | ${pct(g.carbsG, macros.carbG)} |`);
  md.push(`| Fat | ${r1(macros.fatG)} g | ${r1(g.fatG)} g | ${pct(g.fatG, macros.fatG)} |`);
  md.push(`| Fibre | ≥ ${fibreFloor.toFixed(1)} g (floor) | ${r1(g.fibreG ?? 0)} g | ${(g.fibreG ?? 0) >= fibreFloor ? "floor met" : "below floor (yields to kcal)"} |`);
  md.push(`| Sodium | — | ${Math.round(g.sodiumMg ?? 0)} mg | — |`);
  md.push("");

  const pK = Math.abs(((g.kcal - macros.totalKcal) / macros.totalKcal) * 100);
  const pP = Math.abs(((g.proteinG - macros.proteinG) / macros.proteinG) * 100);
  if (pK > 5 || pP > 5) allWithinPair = false;
  md.push(
    `**Protected pair:** kcal ${pK <= 5 ? "✓" : "✗"} ±${pK.toFixed(1)}% · protein ${pP <= 5 ? "✓" : "✗"} ±${pP.toFixed(1)}% (both must be ≤ 5%).`
  );
  md.push("");

  let fillerCount = 0;
  let badGrams = 0;
  for (const slot of plan.slots) {
    const templateIds = new Set(slot.primary.template.ingredients.map((i) => i.foodId));
    md.push(`### ${slot.slot} — ${slot.primary.template.name}`);
    const lines = slot.primary.scaledIngredients.map((ing) => {
      const isFiller = !templateIds.has(ing.foodId);
      if (isFiller) fillerCount++;
      if (!Number.isFinite(ing.grams) || ing.grams <= 0) badGrams++;
      md.push(`- ${ing.name} — ${ing.grams} g${isFiller ? " _(filler)_" : ""}`);
      return `      ${ing.name} ${ing.grams}g${isFiller ? "   ⟵ FILLER" : ""}`;
    });
    md.push("");
    console.log(`  [${slot.slot}] ${slot.primary.template.name}`);
    console.log(lines.join("\n"));
  }
  totalBadGrams += badGrams;
  console.log(`  fillers added: ${fillerCount};  out-of-bound/zero-gram ingredients: ${badGrams}`);
  md.push(`_Fillers added: ${fillerCount}. Out-of-bound / zero-gram ingredients: ${badGrams}._`);
  md.push("");
}

md.push("---");
md.push("");
md.push(
  `**Merge bar:** protected pair (kcal + protein) within ±5% on both days: ${allWithinPair ? "PASS" : "FAIL"}. ` +
    `Out-of-bound / zero-gram ingredients across both days: ${totalBadGrams}.`
);
md.push("");

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "out", "stage2-sample-plans.md");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, md.join("\n"), "utf8");
console.log(`\n📄 wrote ${outPath}`);
