/**
 * Practical food-quantity rounding.
 *
 * The engine's scaler used to call `Math.round(grams)` — 1-gram precision
 * everywhere. Roberto's #4 feedback called this out: "the food quantities
 * generated by the app are very uneven and not very practical." He pointed at
 * rounding rules established for the macro planner. The v4.4 spec defines
 * tolerance bands and per-ingredient floors/ceilings but is silent on
 * gram-level rounding, so we apply sensible defaults here:
 *
 *   • ≥ 20 g  → round to the nearest 5 g    (e.g. 93 → 95, 187 → 185)
 *   • <  20 g → round to the nearest 1 g    (e.g. 11.4 → 11)
 *
 * Unit-snapping (1 uovo = 50 g, 1 mela = 150 g, 1 vasetto yogurt = 150 g…)
 * is a follow-up — it needs the food DB to carry unit-weight tags so we can
 * look up by `foodId` rather than fragile name matching.
 *
 * Pure, side-effect-free; tested in __tests__/rounding.test.ts.
 */

export interface RoundingOptions {
  /** Step (g) for ingredients at or above `smallThreshold`. */
  solidStep: number;
  /** Threshold (g) below which `smallStep` is used. */
  smallThreshold: number;
  /** Step (g) for ingredients below `smallThreshold`. */
  smallStep: number;
}

/** Spec-aligned defaults (May 2026). */
export const DEFAULT_ROUNDING: RoundingOptions = {
  solidStep: 5,
  smallThreshold: 20,
  smallStep: 1,
} as const;

/**
 * Round a single ingredient gram value per the rules above. Always returns a
 * non-negative integer. A 0 input stays 0 (omitted ingredient). Positive
 * values are clamped to at least `smallStep` so a tiny portion doesn't round
 * down to zero and disappear from the plan.
 */
export function roundGrams(
  grams: number,
  opts: RoundingOptions = DEFAULT_ROUNDING
): number {
  if (!Number.isFinite(grams) || grams <= 0) return 0;
  const step = grams >= opts.smallThreshold ? opts.solidStep : opts.smallStep;
  const rounded = Math.round(grams / step) * step;
  return Math.max(opts.smallStep, rounded);
}
